### PR TITLE
Add missing C++ files, add methods to Imports.

### LINKED ISSUE #11: Missing mathconstants.hpp - can't install
Hey Davis,

Wanted to mess around with this but having issues installing with R 3.4.4 on a 64-bit linux system. Looks like it's missing a `source/ql/mathconstants.hpp`?

``` r
> devtools::install_github("DavisVaughan/calendarrr")
Downloading GitHub repo DavisVaughan/calendarrr@master
from URL https://api.github.com/repos/DavisVaughan/calendarrr/zipball/master
Installing calendarrr
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpvrbyJD/devtools531f15c54bbc/DavisVaughan-calendarrr-dd7bfba' --library='/home/claytonjy/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

* installing *source* package ‘calendarrr’ ...
** libs
g++  -I/usr/share/R/include -DNDEBUG -I . -I ../inst/include -I"/home/claytonjy/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/claytonjy/R/x86_64-pc-linux-gnu-library/3.4/BH/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c cal_identifiers.cpp -o cal_identifiers.o
In file included from ./ql/errors.hpp:28:0,
                 from ./ql/time/calendar.hpp:29,
                 from cal_identifiers.cpp:1:
./ql/qldefines.hpp:126:32: fatal error: ql/mathconstants.hpp: No such file or directory
compilation terminated.
/usr/lib/R/etc/Makeconf:168: recipe for target 'cal_identifiers.o' failed
make: *** [cal_identifiers.o] Error 1
ERROR: compilation failed for package ‘calendarrr’
* removing ‘/home/claytonjy/R/x86_64-pc-linux-gnu-library/3.4/calendarrr’
Installation failed: Command failed (1)
```

Created on 2018-08-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
(not really; messages didn't show up in reprex so I did that interactively)
<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.4 (2018-03-15)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       America/Detroit             
#>  date     2018-08-23
#> Packages -----------------------------------------------------------------
#>  package   * version date       source        
#>  backports   1.1.2   2017-12-13 CRAN (R 3.4.4)
#>  base      * 3.4.4   2018-03-16 local         
#>  compiler    3.4.4   2018-03-16 local         
#>  curl        3.2     2018-03-28 CRAN (R 3.4.4)
#>  datasets  * 3.4.4   2018-03-16 local         
#>  devtools    1.13.6  2018-06-27 CRAN (R 3.4.4)
#>  digest      0.6.15  2018-01-28 CRAN (R 3.4.4)
#>  evaluate    0.11    2018-07-17 CRAN (R 3.4.4)
#>  git2r       0.23.0  2018-07-17 CRAN (R 3.4.4)
#>  graphics  * 3.4.4   2018-03-16 local         
#>  grDevices * 3.4.4   2018-03-16 local         
#>  htmltools   0.3.6   2017-04-28 CRAN (R 3.4.4)
#>  httr        1.3.1   2017-08-20 CRAN (R 3.4.4)
#>  knitr       1.20    2018-02-20 CRAN (R 3.4.4)
#>  magrittr    1.5     2014-11-22 CRAN (R 3.4.4)
#>  memoise     1.1.0   2017-04-21 CRAN (R 3.4.4)
#>  methods   * 3.4.4   2018-03-16 local         
#>  R6          2.2.2   2017-06-17 CRAN (R 3.4.4)
#>  Rcpp        0.12.18 2018-07-23 CRAN (R 3.4.4)
#>  rmarkdown   1.10    2018-06-11 CRAN (R 3.4.4)
#>  rprojroot   1.3-2   2018-01-03 CRAN (R 3.4.4)
#>  stats     * 3.4.4   2018-03-16 local         
#>  stringi     1.2.4   2018-07-20 CRAN (R 3.4.4)
#>  stringr     1.3.1   2018-05-10 CRAN (R 3.4.4)
#>  tools       3.4.4   2018-03-16 local         
#>  utils     * 3.4.4   2018-03-16 local         
#>  withr       2.1.2   2018-03-15 CRAN (R 3.4.4)
#>  yaml        2.2.0   2018-07-25 CRAN (R 3.4.4)
```

</details>

### PR DESCRIPTION
**Pull request by ClaytonJY**
Package now builds (for me), and can `devtools::check()` w/o any errors. Still 2 warnings and 2 notes.

Closes #11.

### CODE REVIEW

**Comment by DavisVaughan** [comment]
why did we need `methods`? i thought this wasn't necessary anymore

**Comment by DavisVaughan** [comment]
oh i definitely remember pruning `frequency.hpp` at some point. thanks for adding it back if it seems necessary. maybe i did the same with `mathconstants.hpp`

**Comment by ClaytonJY** [comment]
After adding `mathconstants.hpp`, I got the same error for `time/frequency.hpp`, hence adding that as well.

As for importing `methods`, I've got no clue, but since it's in `NAMESPACE`, `devtools` wants to see it in `DESCRIPTION`, too. My `devtools` seems up-to-date from CRAN; `1.13.6`.

**Comment by DavisVaughan** [comment]
oh i see. it was added here:
https://github.com/DavisVaughan/calendarrr/blob/367280bb5cbb3b295f21b14950895f8ba3d35c5e/R/zzz.R#L3

I don't think its actually necessary (that zzz.r file was generated for me by Rcpp skeleton I think), but its not hurting anything.

Thanks!

**Comment by ClaytonJY** [comment]
The two warning/notes I get are these:

```
Status: 2 WARNINGs, 2 NOTEs
checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘cal_add_holidays’ ‘cal_adjust’ ‘cal_advance’
  ‘cal_business_days_between’ ‘cal_create’ ‘cal_end_of_month’
  ‘cal_get_calendars’ ‘cal_get_holidays’ ‘cal_is_business_day’
  ‘cal_is_end_of_month’ ‘cal_is_holiday’ ‘cal_is_holiday_or_weekend’
  ‘cal_is_weekend’ ‘cal_remove_holidays’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.

checking for GNU extensions in Makefiles ... WARNING
Found the following file(s) containing GNU extensions:
  src/Makevars
Portable Makefiles do not use GNU extensions such as +=, :=, $(shell),
$(wildcard), ifeq ... endif. See section ‘Writing portable packages’ in
the ‘Writing R Extensions’ manual.

checking if this is a source package ... NOTE
Found the following apparent object files/libraries:
  src/ql/errors.o src/ql/time/businessdayconvention.o
  src/ql/time/calendar.o src/ql/time/calendars/target.o
  src/ql/time/calendars/unitedkingdom.o
  src/ql/time/calendars/unitedstates.o
  src/ql/time/calendars/weekendsonly.o src/ql/time/date.o
  src/ql/time/period.o src/ql/time/timeunit.o src/ql/time/weekday.o
  src/ql/utilities/dataformatters.o
Object files/libraries should not be included in a source package.

checking installed package size ... NOTE
  installed size is  5.3Mb
  sub-directories of 1Mb or more:
    libs   5.0Mb
See
  ‘/home/claytonjy/Code/claytonjy/calendarrr.Rcheck/00check.log’
for details.
```

First warning will be fixed naturally, second would require editing `Makevars`. I'll see what happens if I remove all the `*.o` files, but I can't imagine you can do anything about the last one.

This is `devtools::check()` so you might not get all/any of these on R CMD check?

**Comment by DavisVaughan** [comment]
The `Makevars` piece seems to not like my use of `$(wildcard)`.

The `.o` one can probably be fixed with some kind of cleanup of `.Rbuildignore`.

The last note about size worries me. I'm not sure what is bloating it and if I can fix it.

**Comment by ClaytonJY** [comment]
On the `Makevars`/`wildcard` I see [this from Dirk](https://github.com/RcppCore/RcppParallel/issues/53#issuecomment-344746590), but adding `SystemRequirements: GNUmake` to `DESCRIPTION` doesn't seem to affect `devtools::check()`. Not sure if other fix suggested is viable/worth it.

Even less sure about the `lib` size; never seen this, no experience with Rcpp in general either.

**Comment by DavisVaughan** [comment]
Rather than doing wildcard, I can just list all the files to build individually. It will be painful the first time but I can probably make a script that prints them all out for me that I can copy paste. I imagine that once it gets finalized then I won't have to alter it any more.

I'm finally understanding this section of R Extensions that talks about exactly this issue. But I still can't quite understand what their "best approach" means.
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Compiling-in-sub_002ddirectories

Yea this is my first serious venture into Rcpp so I'm in the deep end right now haha

**Pull request merged**
